default: 00 01 02

00:
	python $(shell echo $@*/)emit.py | tee $(shell echo $@*/)output.graph.py
01:
	python $(shell echo $@*/)emit.py | tee $(shell echo $@*/)output.graph.py
02:
	python $(shell echo $@*/)emit.py | tee $(shell echo $@*/)output.graph.py
